#!/usr/bin/env bash
# Display listening TCP/UDP sockets
echo "Active Internet connections (only servers)"
ss -tulnp

# Display listening UNIX domain sockets
echo "Active UNIX domain sockets (only servers)"
ss -xlnp
