#!/usr/bin/env bash
# Change localhost and facebook.com IP resolution

# Remove existing localhost and facebook.com entries
sudo grep -v "localhost" /etc/hosts | sudo grep -v "facebook.com" | sudo tee /etc/hosts.tmp > /dev/null

# Add the required lines
echo -e "127.0.0.2\tlocalhost\n8.8.8.8\tfacebook.com" | sudo tee -a /etc/hosts.tmp > /dev/null

# Replace /etc/hosts with updated version
sudo mv /etc/hosts.tmp /etc/hosts
